[project]
authors = ["Cyrill <cyrill.zadra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community"]
description = "Add a short description here"
name = "build-llm-from-scratch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
requests = ">=2.32.3,<3"
tiktoken = "0.7.0"

