[project]
authors = ["Cyrill <cyrill.zadra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "build-llm-from-scratch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.2.0,<26"
requests = ">=2.32.3,<3"
tiktoken = ">=0.9.0,<0.10"
regex = ">=2024.11.6,<2025"
pytorch = ">=2.6.0,<3"
